name: Lint Code Base

on:
  [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "installation"
        run: pip install black
      - name: "black"
        run: black . --check -l 120 --diff --color
